apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravhub.fullname" . }}
  labels:
    {{- include "ravhub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    {{- if .Values.docker.ports.enabled }}
    # Dynamic Docker registry ports
    {{- range $port := untilStep (int .Values.docker.ports.startPort) (int (add1 .Values.docker.ports.endPort)) 1 }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: docker-{{ $port }}
      {{- if eq $.Values.service.type "NodePort" }}
      nodePort: {{ $port }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "ravhub.selectorLabels" . | nindent 4 }}
